services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - database:/db
    links:
      - "model:model"
  model:
    build: ./utilities
    ports: 
    - "5000:5000"
volumes:
  database: